### ISSUE TITLE
FPing Continuous 100% Packet Loss

### ISSUE THREAD

**Issue by MHammett** [oetiker/SmokePing#109]
My graphs are showing 100% packet loss. I stopped the smokeping service and ran smokeping --debug and saw this:

`FPingContinuous: Executing /usr/bin/fping -l -B1 -r1 -p 950 -b5000 -t1500 -p1500 -S50.31.0.191 -O0x20 XXX.XXX.XXX.XXX ZZZ.ZZZ.ZZZ.ZZZ YYY.YYY.YYY.YYY
FPingContinuous: No data exists - returning undef`

I run that command and I get data.
`root@smokeping:/usr/share/perl5/Smokeping/probes# /usr/bin/fping -l -B1 -r1 -p 950 -b5000 -t1500 -p1500 -S50.31.0.191 -O0x20 XXX.XXX.XXX.XXX ZZZ.ZZZ.ZZZ.ZZZ YYY.YYY.YYY.YYY
XXX.XXX.XXX.XXX : [0], 4096 bytes, 2.69 ms (2.69 avg, 0% loss)
ZZZ.ZZZ.ZZZ.ZZZ  : [0], 4096 bytes, 2.91 ms (2.91 avg, 0% loss)
YYY.YYY.YYY.YYY : [0], 4096 bytes, 14.5 ms (14.5 avg, 0% loss)
XXX.XXX.XXX.XXX : [1], 4096 bytes, 2.49 ms (2.59 avg, 0% loss)
ZZZ.ZZZ.ZZZ.ZZZ  : [1], 4096 bytes, 2.69 ms (2.80 avg, 0% loss)
YYY.YYY.YYY.YYY : [1], 4096 bytes, 12.9 ms (13.7 avg, 0% loss)
XXX.XXX.XXX.XXX : [2], 4096 bytes, 2.44 ms (2.54 avg, 0% loss)
ZZZ.ZZZ.ZZZ.ZZZ  : [2], 4096 bytes, 2.61 ms (2.73 avg, 0% loss)
YYY.YYY.YYY.YYY : [2], 4096 bytes, 12.7 ms (13.4 avg, 0% loss)
XXX.XXX.XXX.XXX : [3], 4096 bytes, 2.23 ms (2.46 avg, 0% loss)
ZZZ.ZZZ.ZZZ.ZZZ  : [3], 4096 bytes, 2.70 ms (2.72 avg, 0% loss)
YYY.YYY.YYY.YYY : [3], 4096 bytes, 11.1 ms (12.8 avg, 0% loss)`

**Comment by lelutin** [comment]
@MHammett which version of fping are you using? and under which distro/release?

if you run this, do you see the same output as me?

~~~
root@debian-9-amd64:~# getcap $(which fping)
/usr/bin/fping = cap_net_raw+ep
~~~

if not, try `setcap cap_net_raw+ep /usr/bin/fping`  (e.g. as recommended in #112 for a different symptom)

**Comment by s1shed** [comment]
> My graphs are showing 100% packet loss. I stopped the smokeping service and ran smokeping --debug and saw this:
> 
> `FPingContinuous: Executing /usr/bin/fping -l -B1 -r1 -p 950 -b5000 -t1500 -p1500 -S50.31.0.191 -O0x20 XXX.XXX.XXX.XXX ZZZ.ZZZ.ZZZ.ZZZ YYY.YYY.YYY.YYY FPingContinuous: No data exists - returning undef`


I see the same. Additionally at the bottom of the `--debug` run I also see

```
FPingContinuous: Input pipe has been closed - exiting
```

**Comment by lelutin** [comment]
@s1shed I think the same questions that I asked @MHammett would also apply to your case:

which linux distribution are you using? which release of the distro? what versions of smokeping and fping are you using?

also, if you run `getcap $(which fping)` do you see that it has the `cap_net_raw+ep` capability?

**Comment by nicolatron** [comment]
Hello,

**Comment by nicolatron** [comment]
Hello, 

I'm having a similar issue.

Distro Debian 10.3.

getcap $(which fping)
/usr/bin/fping = cap_net_raw+ep

fping --version
fping: Version 4.2

smokeping --version
2.007003

In /var/log/messages

Mar  3 11:37:30 alacran smokeping[28502]: FPingContinuous: Adding 20 lost pings to a.b.c.d due to insufficient data

Running --debug shows:
[...]
FPingContinuous: Executing /usr/bin/fping -l -B1 -r1 -p 14250 -b5000 -t1500 -p1500 a.b.c.d
[...]
And at the end of it:
FPingContinuous: Input pipe has been closed - exiting

Running the fping command by hand...

root@alacran:/var/lib/smokeping/Internet# /usr/bin/fping -l -B1 -r1 -p 14250 -b5000 -t1500 -p1500 a.b.c.d
a.b.c.d : [0], 4096 bytes, 38.3 ms (38.3 avg, 0% loss)
a.b.c.d : [1], 4096 bytes, 33.3 ms (35.8 avg, 0% loss)
a.b.c.d : [2], 4096 bytes, 32.1 ms (34.6 avg, 0% loss)
a.b.c.d : [3], 4096 bytes, 29.8 ms (33.4 avg, 0% loss)
a.b.c.d : [4], 4096 bytes, 145 ms (55.7 avg, 0% loss)
a.b.c.d : [5], 4096 bytes, 29.2 ms (51.3 avg, 0% loss)
a.b.c.d : [6], 4096 bytes, 46.4 ms (50.6 avg, 0% loss)
a.b.c.d : [7], 4096 bytes, 25.8 ms (47.5 avg, 0% loss)
a.b.c.d : [8], 4096 bytes, 31.1 ms (45.7 avg, 0% loss)
[...]
