### ISSUE TITLE
smokeping 2.6.8 memory leak(OOM)

### ISSUE THREAD

**Issue by Jerry-Fix** [oetiker/SmokePing#12]
We deploy smokeping 2.6.8 as master/slave mode in our serval IDCs, after running a long time, all our servers occured out of memory, and the whole machine hang, We have to warm reboot the machine.  
The machine(Ubuntu 10.04.3 x86_64 & CentOS 6.0) only run smokeping 2.6.8 and have no other services.

**Comment by vaisk1** [comment]
Version 2.6.11.
I have the same exact problem, I am using about 500 targets at the moment.
The memory use is growing about 15MB per minute.

**Comment by vaisk1** [comment]
Version 2.6.11.
I have the same exact problem, I am using about 500 targets at the moment.
The memory use is growing about 15MB per minute.

I update the config files on average every 15 minutes of all the targets and reload the daemon every minute, it could be that it is related to this, rather than to the monitoring itself.

update: I have confirmed that it is the reload that causes the memory use to raise, to reproduce just put a while loop reloading the daemon every 2 seconds and run ps aux|grep smokeping.
