### ISSUE TITLE
I don't want my Master to poll devices...I just need Slave to poll and send data to Master.

### ISSUE THREAD

**Issue by KalyanKB** [oetiker/SmokePing#133]
HI,
I don't want my Master to poll devices...I just need Slave to poll and send data to Master.
But as my default configurations, I am getting graphs containing Master and slave names..

How to block the Master to poll the devices.

Thanks in Advance

**Comment by tonydm** [comment]
I haven't tried this kind of setup, but have you tried removing all "local" targets, i.e. + Local -> ++ LocalMachine -> host = localhost?

**Comment by Strykar** [comment]
@KalyanKB, @ltfish is right, read https://github.com/oetiker/SmokePing/wiki/FAQ -
1. Why is the master polling a target I only want the slave to poll?
Because you told it to? Or rather, because you didn't tell it not to! See: [`nomasterpoll` in the docs](http://oss.oetiker.ch/smokeping/doc/smokeping_config.en.html)

**Comment by Strykar** [comment]
@oetiker Could this be closed?
