### ISSUE TITLE
New 2.7.3 release breaks old fping versions

### ISSUE THREAD

**Issue by KnoAll** [oetiker/SmokePing#146]
If you have an older version of fping the new 2.7.3 will no longer run those probes and will silently fail. perhaps a message to alert the user or something? I'm working on automating update of fping in my appliance to compensate.

**Comment by genewitch** [comment]
fping -4
fping: invalid option -- '4'
see 'fping -h' for usage information

**Comment by genewitch** [comment]
spoonfeed time:

>git clone https://github.com/schweikert/fping.git
>cd fping
>sudo apt install autoconf #probably
>./autogen.sh
>./configure
>make
>sudo make install

edit /etc/smokeping/config.d/Probes so 
`binary = /usr/local/sbin/fping`

done

**Comment by lelutin** [comment]
@KnoAll I believe this was caused by the change I submitted to fix newer versions of fping

could you give a bit more details about your distro, release, fping version (and is it installed with a package?)

... the older versions of fping are split in two binaries and they unfortunately don't have `-4` and `-6` options to select TCP protocol version.

if you're able to upgrade fping to a more recent version it would be best, but if the old versions are still shipped with a distro/release that's still supported for some time, then it might make sense to keep support for the "old ways"

**Comment by lelutin** [comment]
@KnoAll oh hmm I just looked up what version was available in EPEL7 and fping is at 3.10 there, so before the merger of the IPv6 code.

e.g.: http://fedora-epel.mirror.iweb.com/epel/7/x86_64/Packages/f/

@oetiker since all of the rhel-based distros seem to be stuck with the old version of fping for a while, should we add a conditional in the code so that when the option "protocol" to the fping probe is unset, we avoid forcing one of the protocol arguments?

**Comment by oetiker** [comment]
@lelutin yes for the code to detect the version of fping installed would be ideal ... can you PR ?

**Comment by lelutin** [comment]
@oetiker yep, I'll try and work on this in the coming days

**Comment by deajan** [comment]
@lelutin Also breaks current EPEL fping release, since no -4 or -6 parameters are present:
```
# rpm -qa | grep fping
fping-3.10-4.el7.x86_64
# fping -h

Usage: fping [options] [targets...]
   -a         show targets that are alive
   -A         show targets by address
   -b n       amount of ping data to send, in bytes (default 56)
   -B f       set exponential backoff factor to f
   -c n       count of pings to send to each target (default 1)
   -C n       same as -c, report results in verbose format
   -D         print timestamp before each output line
   -e         show elapsed time on return packets
   -f file    read list of targets from a file ( - means stdin) (only if no -g specified)
   -g         generate target list (only if no -f specified)
                (specify the start and end IP in the target list, or supply a IP netmask)
                (ex. fping -g 192.168.1.0 192.168.1.255 or fping -g 192.168.1.0/24)
   -H n       Set the IP TTL value (Time To Live hops)
   -i n       interval between sending ping packets (in millisec) (default 25)
   -I if      bind to a particular interface
   -l         loop sending pings forever
   -m         ping multiple interfaces on target host
   -n         show targets by name (-d is equivalent)
   -O n       set the type of service (tos) flag on the ICMP packets
   -p n       interval between ping packets to one target (in millisec)
                (in looping and counting modes, default 1000)
   -q         quiet (don't show per-target/per-ping results)
   -Q n       same as -q, but show summary every n seconds
   -r n       number of retries (default 3)
   -s         print final stats
   -S addr    set source address
   -t n       individual target initial timeout (in millisec) (default 500)
   -T n       ignored (for compatibility with fping 2.4)
   -u         show targets that are unreachable
   -v         show version
   targets    list of targets to check (if no -f specified)
```

Compilation steps on CentOS 7:
```
mkdir /opt/install/fping && cd /opt/install/fping
wget https://fping.org/dist/fping-4.1.tar.gz
tar xvf fping-4.1.tar.gz
cd fping-4.1.tar.gz
CFLAGS="-O2 -march=native -mtune=native" .configure
make && make install
```

Probe path has been updated accordingly in smokeping config
```
+ FPing
binary = /usr/local/sbin/fping 
```

**Comment by stromnet** [comment]
FYI, if the configured binary name is `fping6` and `-6` is appended, that fails too: https://github.com/schweikert/fping/issues/147

simplest fix is to just use fping binary instead of fping6

**Comment by kluner** [comment]
the following probe declaration works for me on centos7:

`
+ FPing6

binary = /usr/sbin/fping6 # mandatory
blazemode = true
hostinterval = 1.5
mininterval = 0.001
offset = 50%
pings = 20
protocol = 6
sourceaddress = <ipv6 routealbe addr>
step = 60
timeout = 1.5
#tos = 0x20
usestdout = false
`
this is with the default centos7/epel fping/fping6 in /usr/sbin :

- fping-3.10-4.el7.x86_64

and epel smokeping:

- smokeping-2.6.10-3.el7.noarch
