### ISSUE TITLE
getting error while installing new version of smokeping on ubuntu 12

### ISSUE THREAD

**Issue by krishnabagal** [oetiker/SmokePing#150]
/usr/src/smokeping-2.7.3# make install
Making install in thirdparty
make[1]: Entering directory `/usr/src/smokeping-2.7.3/thirdparty'
  GEN      touch
FCGI is up to date. (0.78)
CGI is up to date. (4.40)
CGI::Fast is up to date. (2.13)
Config::Grammar is up to date. (1.12)
Socket6 is up to date. (0.29)
IO::Socket::SSL is up to date. (2.060)
Digest::HMAC_MD5 is up to date. (1.01)
Net::Telnet is up to date. (3.04)
Net::OpenSSH is up to date. (0.78)
Net::SNMP is up to date. (v6.0.1)
Net::LDAP is up to date. (0.65)
Net::DNS is up to date. (1.19)
IO::Pty is up to date. (1.12)
LWP is up to date. (6.36)
Authen::Radius is up to date. (0.29)
Path::Tiny is up to date. (0.108)
  GEN      touch
make[2]: Entering directory `/usr/src/smokeping-2.7.3/thirdparty'
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/usr/src/smokeping-2.7.3/thirdparty'
make[1]: Leaving directory `/usr/src/smokeping-2.7.3/thirdparty'
Making install in doc
make[1]: Entering directory `/usr/src/smokeping-2.7.3/doc'
  GEN      Smokeping_probes_AnotherCurl.pod
Resetting LC_NUMERIC failed probably because your international setup of the LC_ALL to "en_US.UTF-8" is overridding LC_NUMERIC.  Setting LC_ALL is not compatible with smokeping... at ../lib/Smokeping.pm line 47.
Compilation failed in require.
BEGIN failed--compilation aborted.
make[1]: *** [Smokeping_probes_AnotherCurl.pod] Error 255
rm Smokeping_probes_AnotherCurl.pod
make[1]: Leaving directory `/usr/src/smokeping-2.7.3/doc'
make: *** [install-recursive] Error 1

**Comment by lelutin** [comment]
wow that error message is not very clear.

the build seems to be erroring out during compilation of documentation. @krishnabagal is it possible that your ubuntu system is missing the build requirements to make documentation?

you could try to install them with this command to use the ubuntu package's info about build requirements:

~~~
apt-get build-dep smokeping
~~~

**Comment by lelutin** [comment]
ah! wait, I've just hit the same issue when trying to call smokeinfo.

the error message's important part is apparently `Resetting LC_NUMERIC failed probably because your international setup of the LC_ALL to "en_US.UTF-8" is overridding LC_NUMERIC. Setting LC_ALL is not compatible with smokeping`

if I change LC_ALL, then I'm able to run smokeinfo:

~~~
LC_ALL=C smokeinfo /etc/smokeping/config
~~~

maybe your build needs to clear out LC_ALL. in the debian package the following lines are present in the "rules" file in order to do this before starting the build:

~~~
# smokeping doesn't like building with your locale
unexport LC_ALL
~~~

**Comment by krishnabagal** [comment]
thnx for update...!!!

had use blow command and its work for me :)

`export` `LC_ALL=C`
