### ISSUE TITLE
Add an option to select the interface being used for FPing.

### ISSUE THREAD

**Issue by kitlith** [oetiker/SmokePing#192]
`fping -I` allows you to ping based on interface, this is useful for situations where you want to monitor multiple network mediums -- i.e. wifi and ethernet.

I've modified the FPing module for this locally, by adding:
```
sub targetvars {
        my $class = shift;
        return $class->_makevars($class->SUPER::probevars, {
                interface => {
                        _re => '[0-9a-zA-Z]+',
                        _example => 'eth0',
                        _doc => <<DOC,
The fping "-I" parameter, Set the interface used for outgoing ICMP packets.
DOC
                },
        });
}
```
near the bottom of the file and

```
push @params, "-I$self->{properties}{interface}" if $self->{properties}{interface};
```
inside the ping function.

I don't know that this is the best way to accomplish this, etc.

**Comment by oetiker** [comment]
that looks good, if I make this into a PR, I will be glad to merge it.

**Comment by Marctraider** [comment]
Wow, I was just looking for the same thing.

I'm currently running a redundant setup through a tunnel, and I need to change states whenever one of the bad behaving WAN interfaces go weird, hence the need for ping bind inteface 📦 

@kitlith Thanks this saves me some time, I will try it tomorrow.

**Comment by kitlith** [comment]
For the record, I don't think that modification worked... i ended up switching to a setup w/ telegraf+influxdb+grafana

**Comment by Marctraider** [comment]
> 
> 
> For the record, I don't think that modification worked... i ended up switching to a setup w/ telegraf+influxdb+grafana

Guess I'll have to find another solution as well then, thanks for the heads up!

**Comment by Marctraider** [comment]
@kitlith I tried it with -I and didnt work, with --iface= it seemed to according to tcpdump on interface.

**Comment by stephanecollot** [comment]
That would a great feature!

**Comment by grdnkln** [comment]
I would like to see this feature too.

I was looking for a way to do this because I am setting up Smokeping to run on a Raspberry Pi. I needed a way to specify whether Smokeping is pinging via the eth0 interface, or the wlan0 interface. This way I could monitor my servers and stuff via the wired network, but also have a few specific targets that send ping via the wlan0 interface to monitor the quality of the wireless network.

I ended up doing something similar to @kitlith above and I've modified FPing.pm, except instead of adding target parameters, I added them as probe parameters. 

Here's the changes I made to FPing.pm:

in the "probevars()" function, add the new parameter:
```
                interface => {
                        _re => '[a-zA-Z0-9]+',
                        _example => 'eth0',
                        _doc => "The name of the network interface to perform the ping on.",

                },
```

and in the "pings()" function, use the parameter when calling the fping binary:
```
    push @params, "--iface=$self->{properties}{interface}" if $self->{properties}{interface};
```

Then to use it, add new probes to the "Probes" config file:
```
# Interface-specific Probes
++ FPingProbeeth0
interface = eth0

++ FPingProbewlan0
interface = wlan0
``` 

And finally use those probes in the "Targets" config file:
```
++ Test1
menu = Test1
title = Test1
host = 192.168.1.1
probe = FPingProbeeth0

++ Test2
menu = Test2
title = Test2
host = 192.168.1.1
probe = FPingProbewlan0
```

It seems to work very well.

**Comment by saaly182** [comment]
@grdnkln - were you planning to create a PR for your changes? I'm happy to do it if you want.

**Comment by Strykar** [comment]
@grdnkln Please create a PR

**Comment by grdnkln** [comment]
Thank you @saaly182 for doing the PR for me, I am still learning and don't know how to do that. :) Awesome that this is in the code now!

**Comment by saaly182** [comment]
@grdnkln - I'm new to this, too, and still mostly confused! :)
