### ISSUE TITLE
Example: how to list historic outages?

### ISSUE THREAD

**Issue by jrr** [oetiker/SmokePing#240]
I'm using SmokePing to keep an eye on my ISP's performance. The graphs are great, but another question I hope to answer is _"over the past month, when has the connection significantly degraded?"_.

In more technical terms, I'd like to list instances of e.g. three consecutive samples of 50%+ packet loss.

(Then I might be able to detect patterns, like "weeknights" or "Tuesday mornings")

I've spent some time with the [SmokePing](https://oss.oetiker.ch/smokeping/doc/index.en.html) and [RRDTool](https://oss.oetiker.ch/rrdtool/tut/index.en.html) docs but haven't found an example of something like this.

Can someone point me in the right direction?

**Comment by vlasakjiri** [comment]
Have you found how to do this? I have a similar use case where my internet will stop working completlety for ~30 seconds. Unfortunately these outages are hard to see in smokeping because when internet isn't working, no graphs are drawn. For example here i got outage at around 20:40.
![image](https://user-images.githubusercontent.com/34455248/107432511-5c84c100-6b28-11eb-89e9-3151456cf1c8.png)

**Comment by pklausner** [comment]
The quick fix is to log any loss with this *** Alerts *** definition:
```
+anyloss
type = loss
pattern = >=0%,>0%
edgetrigger = no
comment = at least 1 ping per round failed
```
Then use the logfile/syslog analyser of your choice to ferret out the precise times counts of loss. This avoids all the interpolation which rrdtool does and is not helping in this usecase.
