### ISSUE TITLE
1 Ping per Second rrd

### ISSUE THREAD

**Issue by RealOkami** [oetiker/SmokePing#250]
Can someone tell me how to get 1 ping per second just contious not 20 in 5 minutes?
I cant seem to get the rrd running then.

**Comment by dagelf** [comment]
I've given up on this and consoled myself with getting close enough. When editing these variables, know that you will lose all your history - and you'll have to `rm -rf /var/lib/smokeping`. 

But you can edit `/etc/smokeping/config.d/Database`:

```
*** Database ***

step     = 10
pings    = 7

# consfn mrhb steps total

AVERAGE  0.5   1  10080
AVERAGE  0.5  12  43200
    MIN  0.5  12  43200
    MAX  0.5  12  43200
AVERAGE  0.5 144   7200
    MAX  0.5 144   7200
    MIN  0.5 144   7200
```

You probably want to add a 0 or two to the last column there, if you want history going back more than a few weeks. But also know that this will increased the RRD's by several GB's.

**Comment by dagelf** [comment]
If exact per second pings do actually become possible, the UI will also need to change so as to not refresh the whole page every step interval.

**Comment by dagelf** [comment]
Another note: if you do this, and you have too many hosts, timeouts cause some other hosts not to get pinged due to the default delays.. if there's timeouts on some hosts, you'll be missing data for other hosts.  

Also, FPingContinuous doesn't have anything to do with this, it just means that FPing won't be started and stopped every interval time.
