### ISSUE TITLE
RRD Error

### ISSUE THREAD

**Issue by limpep** [oetiker/SmokePing#264]
Hi,

got the most recent docker image `ghcr.io/linuxserver/smokeping:latest` and getting the following error

`
RRDs::info /data/Europe/Switzerland/SBB.rrd: ERROR: '/data/Europe/Switzerland/SBB.rrd' is too small (should be 2986716 bytes) at /usr/share/perl5/vendor_perl/Smokeping/RRDtools.pm line 113
`

Running on a Raspberry Pi 4.
```
Linux raspberrypi 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux
OS: Raspbian GNU/Linux 10 (buster) armv7l
```

**Comment by jpdsceu** [comment]
Can confirm same issue here also on Raspberry Pi 4 5.10.11-v7l+

**Comment by 123WTF456** [comment]
Still exists, just tried updating

**Comment by nathan-dan** [comment]
I’d forgotten about the issue & updated to smokeping:latest, only to get the same error as reported above. That’s when I remembered there was a reason for setting a version instead of latest. ls159 is currently the latest and ls113 is the last working version for myself. ls114 is when it was based on Alpine 3.13. Perhaps that is the underlying issue?
