### ISSUE TITLE
Timezone wrong

### ISSUE THREAD

**Issue by TheLion** [oetiker/SmokePing#321]
Hi,

My SmokePing (running on Docker) time in the graphs is off by two hours. I looked through the config files and didn't find an (obvious) setting to set the timezone.

Also tried the TZ variable in Docker, but that didn't change anything. Did check previous issues, but couldn't find anything to do with timezones.

Is there an option to pass/set the correct timezone in SmokePing running on Docker?

**Comment by fuzzyeric** [comment]
This seems to come around often.  See, e.g., https://lists.oetiker.ch/pipermail/smokeping-users/2013-November/005371.html

If the SmokePing v. 2.7.3 graphs (upgrading to 2.8.2 in a couple of weeks) were submitted by my students, I would dock a half point for the missing TZ indicator in the lower-right timestamp.

I modified my /etc/smokeping/basepage.html to insert the <p>...</p> line below.  (Note: **ALL** my servers's clocks are GMT/UTC and **ALL** logging is done in GMT/UTC, with NTP synchronization among the servers so that timebases are inter-comparable.  I really, really, really wish it were possible to do all of this in TAI...)

`<div class="main">
    <h1><##title##></h1>
    <h2><##remark##></h2>
    <p><font color="red">Warning/note: all dates/times are in GMT/UTC.</font></p>

    <div class="overview">
`

Would it be possible to get the TZ listed by default on the timestamps in the lower-right.

Additionally, could the documentation at https://oss.oetiker.ch/smokeping/doc/smokeping_config.en.html for Presentation:+overview:strftime and Presentation:+detail:strftime correctly indicate that these stamps are in the lower-_right_.
