### ISSUE TITLE
slaves die when master has new config

### ISSUE THREAD

**Issue by sethlyons** [oetiker/SmokePing#44]
from logs:

```
Tue Aug 11 20:08:51 2015 - Sent data to Server and got new config in response.
Tue Aug 11 20:08:51 2015 - server has new config for me ... HUPing the parent
Tue Aug 11 20:08:53 2015 - Sent data to Server and got new config in response.
Tue Aug 11 20:09:09 2015 - Sent data to Server and got new config in response.
Tue Aug 11 20:09:09 2015 - server has new config for me ... HUPing the parent
Tue Aug 11 20:09:09 2015 - ERROR: no instance of SmokePing running (pid 38550)?
```

i am running smokeping 2.006011 on freebsd 10.1-RELEASE with perl 5.18.4.  from my troubleshooting, it seems that the HUP that smokeping sends actually kills the process.  when i test sending a HUP manually, it works as expected.

**Comment by oetiker** [comment]
anything in the log ? famous last words ?

**Comment by sethlyons** [comment]
Not sure what you mean...my original post had the lines from the smokeping
log.

**Comment by oetiker** [comment]
if smokeping was not running, it could not be writing the last line ... it rather seems that there is something wrong with the pid file

**Comment by sethlyons** [comment]
see below ps output from pre- and post-reload.  note that the main process is gone; the probes slowly die off.  the pidfile still exists even though the process doesn't.
```
0 hostname(~) % ps awwxu | grep smokeping
root   18518   0.0  4.6 192056 47512  -  I    Wed04PM     0:08.11 /usr/local/bin/smokeping [HPing] (perl)
root   18519   0.0  4.7 192056 47776  -  I    Wed04PM     0:05.27 /usr/local/bin/smokeping [FPing] (perl)
root   22914   0.0  4.6 192056 47628  -  I    Wed05PM     2:50.99 /usr/local/bin/smokeping [HPing] (perl)
root   22915   0.0  4.6 189964 47064  -  I    Wed05PM     1:55.95 /usr/local/bin/smokeping [FPing] (perl)
root   23237   0.0  4.6 192056 47592  -  I    Wed05PM     1:54.46 /usr/local/bin/smokeping [FPing] (perl)
root   23238   0.0  4.6 189964 47072  -  I    Wed05PM     2:53.78 /usr/local/bin/smokeping [HPing] (perl)
root   31079   0.0  4.6 189964 47148  -  I    Tue05PM     0:00.23 /usr/local/bin/smokeping [HPing] (perl)
root   31303   0.0  4.6 189964 47000  -  I    Tue05PM     0:13.63 /usr/local/bin/smokeping [HPing] (perl)
root   38552   0.0  4.6 189964 46976  -  I    Tue07PM     0:02.78 /usr/local/bin/smokeping [FPing] (perl)
root   40798   0.0  4.6 189964 47048  -  I    Tue08PM     2:26.27 /usr/local/bin/smokeping [HPing] (perl)
root   76962   0.0  4.5 189964 45908  -  Is    5:48PM     0:00.01 /usr/local/bin/perl /usr/local/bin/smokeping --master-url=<master>/smokeping.fcgi --cache-dir=/usr/local/var/smokeping --shared-secret=<sercrets file> --logfile=/var/log/smokeping.log
root   76963   0.0  4.6 189964 46992  -  S     5:48PM     0:00.41 /usr/local/bin/smokeping [FPing] (perl)
root   76964   0.0  4.6 189964 46996  -  S     5:48PM     0:00.59 /usr/local/bin/smokeping [HPing] (perl)
slyons 77447   0.0  0.2  18724  2468  0  S+    5:53PM     0:00.00 grep smokeping
0 hostname(~) %
0 hostname(~) % ls -l /usr/local/var/smokeping/pid
-rw-r--r--  1 smokeping  smokeping  6 Aug 13 17:48 /usr/local/var/smokeping/pid
0 hostname(~) %
0 hostname(~) % cat /usr/local/var/smokeping/pid
76962
0 hostname(~) %
0 hostname(~) % ps awwxu | grep smokeping
root   18518   0.0  4.6 192056 47512  -  I    Wed04PM     0:08.11 /usr/local/bin/smokeping [HPing] (perl)
root   18519   0.0  4.7 192056 47776  -  I    Wed04PM     0:05.27 /usr/local/bin/smokeping [FPing] (perl)
root   22914   0.0  4.6 192056 47628  -  I    Wed05PM     2:50.99 /usr/local/bin/smokeping [HPing] (perl)
root   22915   0.0  4.6 189964 47064  -  I    Wed05PM     1:55.95 /usr/local/bin/smokeping [FPing] (perl)
root   23237   0.0  4.6 192056 47592  -  I    Wed05PM     1:54.46 /usr/local/bin/smokeping [FPing] (perl)
root   23238   0.0  4.6 189964 47072  -  I    Wed05PM     2:53.78 /usr/local/bin/smokeping [HPing] (perl)
root   31079   0.0  4.6 189964 47148  -  I    Tue05PM     0:00.23 /usr/local/bin/smokeping [HPing] (perl)
root   31303   0.0  4.6 189964 47000  -  I    Tue05PM     0:13.63 /usr/local/bin/smokeping [HPing] (perl)
root   38552   0.0  4.6 189964 46976  -  I    Tue07PM     0:02.78 /usr/local/bin/smokeping [FPing] (perl)
root   40798   0.0  4.6 189964 47048  -  I    Tue08PM     2:26.27 /usr/local/bin/smokeping [HPing] (perl)
root   76963   0.0  4.6 189964 46992  -  S     5:48PM     0:00.54 /usr/local/bin/smokeping [FPing] (perl)
slyons 77703   0.0  0.2  18724  2468  0  S+    5:54PM     0:00.00 grep smokeping
0 hostname(~) % ls -l /usr/local/var/smokeping/pid
-rw-r--r--  1 smokeping  smokeping  6 Aug 13 17:48 /usr/local/var/smokeping/pid
0 hostname(~) % cat /usr/local/var/smokeping/pid
76962
0 hostname(~) %
```

truss output of the pid while smokeping tries to reload it is below:
```
SIGNAL 20 (SIGCHLD)
sigprocmask(SIG_SETMASK,SIGCHLD,0x0)             = 0 (0x0)
sigreturn(0x7fffffffad80,0x7fffffffad80,0x301,0x1,0xfffffffffffffbc0,0x8017b2b10) = 17 (0x11)
read(4,0x80c9cc000,8192)                         = 0 (0x0)
fstat(4,{ mode=p--------- ,inode=1,size=0,blksize=4096 }) = 0 (0x0)
close(4)                                         = 0 (0x0)
sigprocmask(SIG_SETMASK,SIGHUP|SIGINT|SIGQUIT|SIGILL|SIGTRAP|SIGABRT|SIGEMT|SIGFPE|SIGKILL|SIGBUS|SIGSEGV|SIGSYS|SIGPIPE|SIGALRM|SIGTERM|SIGURG|SIGSTOP|SIGTSTP|SIGCONT|SIGCHLD|SIGTTIN|SIGTTOU|SIGIO|SIGXCPU|SIGXFSZ|SIGVTALRM|SIGPROF|SIGWINCH|SIGINFO|SIGUSR1|SIGUSR2,0x0) = 0 (0x0)
sigaction(SIGHUP,{ SIG_IGN 0x0 ss_t },{ 0x800829ed0 SA_SIGINFO ss_t }) = 0 (0x0)
sigprocmask(SIG_SETMASK,0x0,0x0)                 = 0 (0x0)
sigprocmask(SIG_SETMASK,SIGHUP|SIGINT|SIGQUIT|SIGILL|SIGTRAP|SIGABRT|SIGEMT|SIGFPE|SIGKILL|SIGBUS|SIGSEGV|SIGSYS|SIGPIPE|SIGALRM|SIGTERM|SIGURG|SIGSTOP|SIGTSTP|SIGCONT|SIGCHLD|SIGTTIN|SIGTTOU|SIGIO|SIGXCPU|SIGXFSZ|SIGVTALRM|SIGPROF|SIGWINCH|SIGINFO|SIGUSR1|SIGUSR2,0x0) = 0 (0x0)
sigaction(SIGINT,{ SIG_IGN 0x0 ss_t },{ 0x800829ed0 SA_SIGINFO ss_t }) = 0 (0x0)
sigprocmask(SIG_SETMASK,0x0,0x0)                 = 0 (0x0)
sigprocmask(SIG_SETMASK,SIGHUP|SIGINT|SIGQUIT|SIGILL|SIGTRAP|SIGABRT|SIGEMT|SIGFPE|SIGKILL|SIGBUS|SIGSEGV|SIGSYS|SIGPIPE|SIGALRM|SIGTERM|SIGURG|SIGSTOP|SIGTSTP|SIGCONT|SIGCHLD|SIGTTIN|SIGTTOU|SIGIO|SIGXCPU|SIGXFSZ|SIGVTALRM|SIGPROF|SIGWINCH|SIGINFO|SIGUSR1|SIGUSR2,0x0) = 0 (0x0)
sigaction(SIGQUIT,{ SIG_IGN 0x0 ss_t },{ SIG_DFL 0x0 ss_t }) = 0 (0x0)
sigprocmask(SIG_SETMASK,0x0,0x0)                 = 0 (0x0)
wait4(78200,{ EXITED,val=0 },0x0,0x0)            = 78200 (0x13178)
sigprocmask(SIG_SETMASK,SIGHUP|SIGINT|SIGQUIT|SIGILL|SIGTRAP|SIGABRT|SIGEMT|SIGFPE|SIGKILL|SIGBUS|SIGSEGV|SIGSYS|SIGPIPE|SIGALRM|SIGTERM|SIGURG|SIGSTOP|SIGTSTP|SIGCONT|SIGCHLD|SIGTTIN|SIGTTOU|SIGIO|SIGXCPU|SIGXFSZ|SIGVTALRM|SIGPROF|SIGWINCH|SIGINFO|SIGUSR1|SIGUSR2,0x0) = 0 (0x0)
sigaction(SIGHUP,{ 0x800829ed0 SA_SIGINFO ss_t },{ SIG_IGN 0x0 ss_t }) = 0 (0x0)
sigprocmask(SIG_SETMASK,0x0,0x0)                 = 0 (0x0)
sigprocmask(SIG_SETMASK,SIGHUP|SIGINT|SIGQUIT|SIGILL|SIGTRAP|SIGABRT|SIGEMT|SIGFPE|SIGKILL|SIGBUS|SIGSEGV|SIGSYS|SIGPIPE|SIGALRM|SIGTERM|SIGURG|SIGSTOP|SIGTSTP|SIGCONT|SIGCHLD|SIGTTIN|SIGTTOU|SIGIO|SIGXCPU|SIGXFSZ|SIGVTALRM|SIGPROF|SIGWINCH|SIGINFO|SIGUSR1|SIGUSR2,0x0) = 0 (0x0)
sigaction(SIGINT,{ 0x800829ed0 SA_SIGINFO ss_t },{ SIG_IGN 0x0 ss_t }) = 0 (0x0)
sigprocmask(SIG_SETMASK,0x0,0x0)                 = 0 (0x0)
sigprocmask(SIG_SETMASK,SIGHUP|SIGINT|SIGQUIT|SIGILL|SIGTRAP|SIGABRT|SIGEMT|SIGFPE|SIGKILL|SIGBUS|SIGSEGV|SIGSYS|SIGPIPE|SIGALRM|SIGTERM|SIGURG|SIGSTOP|SIGTSTP|SIGCONT|SIGCHLD|SIGTTIN|SIGTTOU|SIGIO|SIGXCPU|SIGXFSZ|SIGVTALRM|SIGPROF|SIGWINCH|SIGINFO|SIGUSR1|SIGUSR2,0x0) = 0 (0x0)
sigaction(SIGQUIT,{ SIG_DFL 0x0 ss_t },{ SIG_IGN 0x0 ss_t }) = 0 (0x0)
sigprocmask(SIG_SETMASK,0x0,0x0)                 = 0 (0x0)
sigprocmask(SIG_BLOCK,SIGCHLD,0x0)               = 0 (0x0)
munmap(0x80b603000,2134016)                      = 0 (0x0)
process exit, rval = 20
```

**Comment by sethlyons** [comment]
just wanted to follow up on this issue.  are there additional debugs you'd like to see that would help the investigation?

**Comment by oetiker** [comment]
hmmm this is trick, as I am not seeing this here

**Comment by pixall** [comment]
Hi,
unfortunately I'm facing the same problem now, on all slave machines that we installed recently. When config is changed on master and slave gets it via http, slave send itself SIGHUP and then dies. 

Machines which have this problem are running:
- Voyage Linux, based on Debian 8
- linux kernel 3.16.7-ckt9-voyage
- perl v5.20.2
- Smokeping version 2.006009

This problem is _not_ present on our older slaves:
- Voyage Linux, based on Debian 5
- linux kernel 2.6.30-voyage
- perl v5.10.0
- Smokeping version 2.003006 

I have compared related Smokeping.pm code, and it seems to be unchanged. Maybe something has changed in perl or kernel meantime.. I tied to debug it and find what's the problem, but I had no luck with it.

**Comment by sethlyons** [comment]
@oetiker anything else we can provide here?  still seeing this issue with:
* FreeBSD 10.3-RELEASE
* Smokeping 2.006011
* Perl 5.24.1

**Comment by feld** [comment]
I'm constantly seeing this issue as well. Why do the slaves exit at all? If the slave for any reason cannot contact the master it should not exit, but sleep and try again while continuing work with its existing configuration. Slaves should only stop when it receives a SIGTERM.

On FreeBSD you can also kill a smokeping process with a SIGHUP. I have not been able to identify why this happens.

**Comment by yet-another-random-username** [comment]
I did a bit of poking around the code. The only way I can get it to not suicide is to define $SIG{HUP} in kill_smoke. It's as if %SIG has gone non-global for some odd reason.

My perl is 5.24.1 on Debian stretch.

**Comment by ajscam** [comment]
For me, this was an issue caused by my systemd script.

I found this example of systemd script on the internet:
[Service]
ExecStart=/usr/sbin/smokeping --nodaemon --master-url=https://sentry.cogcap.com/smokeping/sm.cgi --cache-dir=/var/lib/smokeping/ --shared-secret=/etc/smokeping/secret.txt
ExecReload=/bin/kill -HUP $MAINPID
StandardError=syslog


With --nodaemon, it looks like smokeping doesn't create a pid file.  But it was finding an old pidfile laying around in /var/lib/smokeping/smokeping.pid (defaults to --cache-dir).

In journalctl, the error is always:
ERROR: no instance of SmokePing running (pid **121174**)?

And pid **121174** is the contents of this stale file.

Seems like smokeping cannot run in nodaemon mode as a Slave.

I'm using this systemd script now, which has resolved the issue for me:

[Service]
ExecStart=/usr/sbin/smokeping --master-url=https://sentry.cogcap.com/smokeping/sm.cgi --cache-dir=/var/lib/smokeping/ --shared-secret=/etc/smokeping/secret.txt --pid-dir /var/run/smokeping
ExecReload=/bin/kill -HUP $MAINPID
StandardError=syslog
Type=forking
PIDFile=/var/run/smokeping/smokeping.pid

**Comment by deajan** [comment]
Thanks you for your systemd file.
I've got my own, but the --nodaemon option saved my headaches.
Here's my full version:
```
[Unit]
Description=Latency Logging and Graphing System
After=syslog.target network.target

[Service]
ExecStart=/opt/smokeping/bin/smokeping --master-url=http://smoke.fmi.fr/smokeping.fcgi --cache-dir=/opt/smokeping/slavecache --shared-secret=/opt/smokeping/etc/shared_secret --pid-dir=/var/run
ExecReload=/bin/kill -HUP $MAINPID
StandardError=syslog
#Type=forking
PIDFile=/var/run/smokeping.pid

[Install]
WantedBy=multi-user.target
```

Note forking is not needed, got updates from master server without restarting the service.

**Comment by lelutin** [comment]
@oetiker from what I can see Smokeping.pm a pid-dir is forced to exist (in cache-dir if no pid-dir was give) when running in "slave" mode.

This seems to be because when there's new configuration coming in from the master, a SIGHUP signal is sent to the parent process so that config is reloaded.
Wouldn't it be possible to achieve this reload without a parent process?
..of course I might be missing something since I didn't inspect all of the forking/subrocess call code.

**Comment by oetiker** [comment]
if you have a different solution, sure, just send a PR

**Comment by Strykar** [comment]
@ajscam @deajan Weird, it creates the pid when `--pid-dir` and `PIDFile=` are specified in with the `--nodaemon` option, so why not use the `--nodaemon` option?

**Comment by Strykar** [comment]
@oetiker Could we get some clarity on using `--nodaemon` on a slave with systemd? I'll create PRs for master and slave systemd unit files.

**Comment by oetiker** [comment]
when smokeping was created there was no systemd ... --nodaemon was manly used for debugging :) so cleaning this up is certainly a good idea ... --nodeaemon should obviously not create a pid ... yes

**Comment by stromnet** [comment]
I had same issue on FreeBSD 11.1 with perl 5.28, managed to unbreak it with fix in #181.

Given how old this ticket is, and without solutions, I guess it's possible that there could be more than one problem involved here, and I just happened to find one of them for my platform?

**Comment by stromnet** [comment]
I've noticed this lack of pid file in nodaemon too, it is *not created*.
I've experimented with running smokeping slaves in docker, which means smokeping running with --nodaemon as master process.  When it tries to SIGHUP itself it fails, since it has created no pidfile, and the old process instead dies (`kill_smoke` calls `die`), and the container with it.

Depending on the system which manages your containers, it will be re-created/restarted, but I think it would be better if it managed to reload itself as intended.

In my case I managed to work around it by manually creating `/tmp/smokeping.pid` with the value `1` (as the main proc in a docker containers always has pid 1). Then I run `exec smokeping --pid-dir /tmp ...`, and now everything works as expected.

The good news is that applying #181 helped on Linux as well, so it was not just a FreeBSD problem (tested on alpine:latest with smokeping-2.7.3 iirc). Without that patch I had same problems as described in my PR.

**Comment by computercolin** [comment]
On the subject of containers and docker, if using an init system, it may be possible to manually create the PID file for smokeping (and keep the output from --nodaemon).

For example with s6 script that execs into smokeping:

https://github.com/computercolin/docker-smokeping-slave/blob/9116956452b700edf683c8a3fe90a6636ec9fca2/root/etc/services.d/smokeping/run#L25
